-- Basic config
require("core.mappings")
require("core.plugins")
require("core.colors")
require("core.configs")

-- Plugins config
require("plugins.mason")
require("plugins.telescope")
require("plugins.lsp")
require("plugins.cmp")
require("plugins.lualine")
require("plugins.gitsigns")
require("plugins.treesitter")
require("plugins.toggleterm")
require("plugins.autopairs")
require("plugins.buffline")
require("plugins.neotree")
require("plugins.whichkey")
require("plugins.dap")
require("plugins.cmaketools")
-- require("plugins.tabnine")
require("plugins.copilot")
require("plugins.leap")
require("plugins.lspsaga")
require("plugins.notify")
require("plugins.cpptools")
require("plugins.highlight")
require("plugins.illuminate")
require("plugins.trouble")
require("plugins.workspaces")
require("plugins.animate")
